;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        helm-M-x
        helm-maybe-exit-minibuffer
        sp-delete-char
        sp-kill-region
        sp-kill-word
        ))

(setq mc/cmds-to-run-once
      '(
        cljr-slash
        sp-backward-delete-char
        ))
